@extends('frontPage.plantillaFormulario')
@section('Titulo')
	Reservas
@stop
@section('body')
	@include('frontPage.formulario')
@stop
@section('areaInformacion')
	@include('frontPage.informacion')
@stop
@section('informacionAbajo')
	@include('frontPage.informacionAbajo')
@stop
