@extends('frontPage.plantilla')
@section('Titulo')
	Reservas
@stop
@section('formulario')
	@include('frontPage.formulario')
@stop
@section('areaInformacion')
	@include('frontPage.informacion')
@stop
@section('informacionAbajo')
	@include('frontpage.informacionAbajo')
@stop